# Generated by Django 3.1.4 on 2021-07-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientcode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100, null=True)),
                ('old_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('expiration', models.DateTimeField(auto_now_add=True, null=True)),
                ('f0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f0fk', to='demo.demo')),
                ('f1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f1fk', to='demo.demo')),
                ('f2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f2fk', to='demo.demo')),
                ('f3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f3fk', to='demo.demo')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='demo.province')),
            ],
        ),
    ]
