# Generated by Django 3.1.4 on 2021-07-16 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientcode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100, null=True)),
                ('f0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f0fk', to='demo.demo')),
                ('f1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f1fk', to='demo.demo')),
                ('f2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='f2fk', to='demo.demo')),
            ],
        ),
    ]
