# Generated by Django 3.1.4 on 2021-07-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_testresult_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demo',
            old_name='f0',
            new_name='f_status',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='demo',
            name='f3',
        ),
    ]
