# Generated by Django 3.1.4 on 2021-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20210720_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
