# Generated by Django 3.1.4 on 2021-07-21 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20210721_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='old_status',
        ),
    ]
