# Generated by Django 3.1.4 on 2021-07-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20210721_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
