# Generated by Django 3.1.4 on 2021-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_status_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
