# Generated by Django 3.1.4 on 2021-07-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_testresult_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
